[package]
name = "luxid-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Core runtime for the Luxid web framework"

[dependencies]
salvo.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
bytes.workspace = true
thiserror.workspace = true
argon2.workspace = true
jsonwebtoken.workspace = true
anyhow.workspace = true
