//! Core runtime for the Luxid web framework.
//!
//! Applications depend on the `luxid` facade crate rather than on this one.

pub mod adapter;
pub mod app;
pub mod auth;
pub mod config;
pub mod container;
pub mod context;
pub mod error;
pub mod http;
pub mod inertia;
pub mod middleware;
pub mod openapi;
pub mod router;
pub mod session;
pub mod validation;

pub use app::App;
pub use auth::{Auth, Hash, Identity, Jwt};
pub use config::Config;
pub use container::{Container, Lifetime, Providers};
pub use context::{Extensions, HttpContext, Params};
pub use error::{Error, Result, ValidationErrors};
pub use http::{Body, Cookie, Request, Response, SameSite};
pub use inertia::{Inertia, InertiaRequest};
pub use middleware::{Action, BoxFuture, Middleware, Next};
pub use openapi::{Operation, ResponseSpec};
pub use router::{Method, ResourceRoutes, Route, RouteInfo, Router};
pub use session::{MemoryStore, Session, SessionData, SessionStore};
pub use validation::{Validate, validate};

/// Re-exports for code generated by `luxid-macros`. Not a stable API.
#[doc(hidden)]
pub mod __private {
    pub use salvo;

    pub use crate::middleware::{Action, BoxFuture, Middleware, Next};
    pub use crate::openapi::{Operation, ResponseSpec};
    pub use crate::router::ResourceRoutes;
    pub use crate::validation::{Validate, rules, validate};
}
