//! The data layer: expressive model ergonomics over SeaORM.

pub mod db;
pub mod factory;
pub mod hooks;
pub mod loading;
pub mod migration;
pub mod model;
pub mod relations;
pub mod schema;

pub use db::{Db, Handle, WithDatabase, WithRollbackDatabase};
pub use factory::{Factory, FactoryBuilder};
pub use hooks::Hooks;
pub use migration::MigrationState;
pub use model::{
    ColumnRef, Paginated, Query, Record, Relatable, delete_by_id, insert, insert_without_hooks,
    update,
};
pub use relations::{Relations, set_strict_relations, strict_relations};
pub use schema::{Column, Table};
pub use sea_orm_migration;

#[doc(no_inline)]
pub use luxid_core::{Error, Result};

/// Re-exported so applications need not depend on SeaORM directly for the
/// common cases.
pub use sea_orm;

/// Re-exports for code generated by `luxid-macros`. Not a stable API.
#[doc(hidden)]
pub mod __private {
    pub use crate::hooks::Hooks;
    pub use crate::loading::{load_belongs_to, load_has_many, load_has_one};
    pub use crate::model::{ColumnRef, Record, Relatable};
    pub use crate::relations::Relations;
    pub use luxid_core::middleware::BoxFuture;
}
